export const responseMessage = {
  UNAUTHORIZED: 'Unauthorized Access',
  INTERNAL_SERVER_ERROR: 'Internal server error.',
  FILE_NOT_FOUND: 'File not found',
  SUCCESSFULLY_DONE: 'Data found successfully.',
  SUCCESSFULLY_UPDATE: 'Data updated successfully.',
  WENT_WRONG: 'Something went wrong',
  NOT_FOUND: 'No data found.',
  UPDATE: 'is updated successfully.',
  ALREADY_EXIST: 'already exist.',
  SIGNED_IN: 'Login successfully.',
  SUCCESS: 'Success',
  FORBIDDEN: 'The server is unable to authorize a particular request.',
  INVALID_USER_CREDENTIALS: 'Username and password is invalid',
};
